spring:
  application:
    name: SubTrack
  datasource:
    url: jdbc:postgresql://postgres:5432/subTrack
    username: user
    password: pass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true