name: "SubTrack"
services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: subTrack
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"
    networks:
      - app-network
  app:
    image: subtrack:v1
    build:
      context: ../
    command: [ "--spring.profiles.active=docker" ]
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge